#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XMath_1._1.x.Resource", IsApplication=true)]

namespace XMath_1._1.x
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int SlideDownAnimation = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int SlideFromLeftAnimation = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int SlideToLeftAnimation = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int SlideUpAnimation = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f05000d
			public const int Correct = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int Error = 2131034124;
			
			// aapt resource value: 0x7f050002
			public const int backgroundColor = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int colorAccent = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int colorPrimary = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int naviBarColor = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int numberColor = 2131034123;
			
			// aapt resource value: 0x7f050005
			public const int signColor = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int statusBarColor = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int textColorPrimary = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int timeElapsedBaseColor = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int timeElapsedBgColor = 2131034122;
			
			// aapt resource value: 0x7f050007
			public const int timeElapsedCorrectColor = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int timeElapsedWrongColor = 2131034120;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Clock = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080009
			public const int answerEditText = 2131230729;
			
			// aapt resource value: 0x7f080002
			public const int correctLabelTextView = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int correctTextView = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int elapsedTextView = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int eventTextView = 2131230725;
			
			// aapt resource value: 0x7f08000c
			public const int historyListView = 2131230732;
			
			// aapt resource value: 0x7f080004
			public const int numberTextView = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int operand1TextView = 2131230726;
			
			// aapt resource value: 0x7f080008
			public const int operand2TextView = 2131230728;
			
			// aapt resource value: 0x7f08000a
			public const int resultTextView = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int scoreTextView = 2131230731;
			
			// aapt resource value: 0x7f080007
			public const int signTextView = 2131230727;
			
			// aapt resource value: 0x7f080000
			public const int timeTextView = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ElapsedTimeDialog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListView_row = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int ApplicationName = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int TimeDialogAnimation = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int XMathTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
